on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.25.5

      - name: Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.4.0

      - name: Format check
        run: make fmt-check

      - name: Static analysis
        run: go vet ./...

      - name: Test
        run: go test -race -coverprofile=coverage.out ./...

      - name: Upload test coverage report
        uses: codecov/codecov-action@v4.5.0
        with:
          file: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
